
version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/rm_container.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/run_container.sh
      timeout: 300
      runas: root
